title: Mrinmoy Haloi
description: >-
  Always programming.
url: https://mrinmoy.is-a.dev
location: Assam, India
email: mrinmoy@duck.com
twitter: _mrinmoy_haloi_
github:  mrinmoyhaloi

sass:
    style: compressed

collections:
  - projects

# development options
host: 0.0.0.0
livereload: true