title: Mrinmoy Haloi
description: >-
  A Front End developer a passion of making great websites.
url: ""
location: Assam, India
email: mrinmoy@duck.com
twitter: _mrinmoy_haloi_
github:  mrinmoyhaloi

# Build settings
plugins:
  - jekyll-feed

sass:
    style: compressed

collections:
  - projects